# Generated by Django 4.0.6 on 2022-07-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_min_order_amount'),
        ('cart', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amount',
            new_name='Item',
        ),
    ]
