# Generated by Django 4.0.6 on 2022-07-23 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_item_created_at_item_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='amount',
            new_name='quantity',
        ),
    ]
