# Generated by Django 4.0.6 on 2022-07-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_rename_amount_item_quantity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='unique_cart'),
        ),
    ]
