# Generated by Django 4.0.6 on 2022-07-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='bill_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
