# Generated by Django 4.0.6 on 2022-07-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_payment_method_order_bill_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Not Paid', 'Not Paid'), ('Success', 'Success'), ('Canceled', 'Canceled'), ('Failed', 'Failed')], default='Not Paid', max_length=20, null=True),
        ),
    ]
